#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.

import string
def solve(s):
    result =[]
    capitalize_next = True
    for char in s:
        if char == " ":
            capitalize_next = True
            result.append(char)
        else:
            if capitalize_next:
                result.append(char.upper())
                capitalize_next = False
            else:
                result.append(char)
        
    return "".join(result)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
